### PR TITLE
Bugfix/members snapshot

### LINKED ISSUE #46: Uncaught (in promise) FirebaseError: Missing or insufficient permissions.
I've signed in successfully with Github but when I go to the "Subscribe" tab I get the following error:

```
Uncaught (in promise) FirebaseError: Missing or insufficient permissions.
``` 

Screenshot 2019-09-25 at 06 30 48

--- 

Browser: Chrome 76
OS: OS X 10.14.6

### PR DESCRIPTION
**Pull request by grudelsud**
this shoud fix #46 

I suspect that lots of people never got to the subscription form because of this bug but never said anything? it would be good to test it?

### CODE REVIEW

File: src/state/reducers/members.js [hunk 1]
```diff
@@ -12,32 +12,39 @@ const initialState = {
...
-    db.collection(DBCollections.members).onSnapshot(({ docs }) => {
-      const members = docs.map(d => d.data())
-      resolve(members)
-    }, reject)
-  }),
-}))
+export const loadMembers = createAction('MEMBERS_SNAPSHOT')
+export const updateMembers = createAction('MEMBERS_UPDATE', members => (members))
+
+export const membersSnapshot = () => {
```
Comment (grudelsud) [inline src/state/reducers/members.js]: this is called once by Authentication when login status changes (i.e. onLogin)
